### PR TITLE
Create 2016-04-22-NetWiCS.markdown

### PR DESCRIPTION
**Pull request by merlinyx**

### CODE REVIEW

**Comment by ohEmily** [comment]
Maybe we could add a little more content before we merge in? Thanks for getting starte!

**Comment by merlinyx** [comment]
Yes... maybe until more photos are up in assets? It is my first time doing this, please teach me anything I need to know! Thank you!

**Comment by ohEmily** [comment]
For sure. @cl3180 just sent them out by email. You should be able to add them to assets yourself by adding them to your local copy of the repo and then committing and pushing those changes.

Let me know if I can help further!

**Comment by ohEmily** [comment]
Oh it looks like @six5532one already added two here:
https://github.com/CUWiCS/cuwics.github.io/blob/master/assets/blog2016/NetWiCS_introspeech1.jpg
https://github.com/CUWiCS/cuwics.github.io/blob/master/assets/blog2016/NetWiCS_introspeech2.jpg

So you can reference those, and when we merge into master, the references will resolve.

**Comment by merlinyx** [comment]
I changed the colors of the pictures a little bit and added some text!

**Comment by ohEmily** [comment]
Great! I think your changes to files in `/assets` didn't get changed, since you take a look at the commit you just made, you only changed the text file you added originally. Make sure to `git add <path/to/filename>` the file(s) you want to add.

**Comment by merlinyx** [comment]
I was making changes in the master branch instead of the patch-1 branch, but after I merged them, they seem good to go! Thank you Emily for helping me learn how to do this!

**Comment by ohEmily** [comment]
No problem!

**Comment by ohEmily** [comment]
If you're wondering, this shows up as a single commit on master because I used the "squash and merge" function on GitHub. "squashing" is a git command where you combine a bunch of commits into one, usually done using the rebase command. The reason I did this is so that we would not have all the intermediate commits (e.g. the ones where you were figuring out how to place the image) in the history. We simply have a single commit showing what you added.

Thanks for taking care of this!

**Pull request merged**
